version: '2'
services:
  scrutiny:
    image: makertorsten/opensprinkler:latest
    container_name: opensprinkler
#    privileged: true
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/opensprinkler:/data
    ports:
      - 8085:8080
    restart: unless-stopped
